# Generated by Django 5.1 on 2024-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mxrecord',
            name='mail_server',
        ),
        migrations.RemoveField(
            model_name='mxrecord',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='srvrecord',
            name='port',
        ),
        migrations.RemoveField(
            model_name='srvrecord',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='srvrecord',
            name='target',
        ),
        migrations.RemoveField(
            model_name='srvrecord',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='txtrecord',
            name='value',
        ),
        migrations.AddField(
            model_name='mxrecord',
            name='fqdn',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srvrecord',
            name='fqdn',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='txtrecord',
            name='fqdn',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
