# Generated by Django 5.1 on 2024-09-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_remove_mxrecord_mail_server_remove_mxrecord_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.AlterField(
            model_name='domain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='datahub.company'),
        ),
    ]
