# Generated by Django 5.1 on 2024-09-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0003_alter_company_options_remove_company_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='datahub.company'),
        ),
    ]
