# Generated by Django 5.1 on 2024-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_alter_domain_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_checked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
