# Generated by Django 5.1 on 2024-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_domain_last_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
