# Generated by Django 5.1 on 2024-09-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='domains', to='datahub.service'),
        ),
    ]
