# Generated by Django 5.1 on 2024-09-22 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0007_domain_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Pattern to look for in DNS records', max_length=255)),
                ('record_type', models.CharField(choices=[('MX', 'MX Record'), ('TXT', 'TXT Record'), ('SRV', 'SRV Record')], help_text='Type of DNS record to check (MX, TXT, SRV)', max_length=3)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='datahub.service')),
            ],
        ),
    ]
