# Generated by Django 5.1 on 2024-09-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0008_servicepattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL of the contact', max_length=500, null=True),
        ),
    ]
