# Generated by Django 5.1 on 2024-09-23 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0009_contact_linkedin_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who created this entity.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('company', 'Company'), ('public', 'Public')], default='private', help_text='Who can access this entity.', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who created this entity.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('company', 'Company'), ('public', 'Public')], default='private', help_text='Who can access this entity.', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who created this entity.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('company', 'Company'), ('public', 'Public')], default='private', help_text='Who can access this entity.', max_length=20),
        ),
    ]
