# Generated by Django 5.1 on 2024-09-23 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0010_company_created_at_company_owner_company_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='owner',
        ),
        migrations.AddField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(help_text='Users who can manage this entity.', related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='owners',
            field=models.ManyToManyField(help_text='Users who can manage this entity.', related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='owners',
            field=models.ManyToManyField(help_text='Users who can manage this entity.', related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
