# Generated by Django 5.1 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0011_remove_company_owner_remove_contact_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lusha_contact_id',
            field=models.CharField(blank=True, help_text='Lusha contact ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name', 'lusha_contact_id')},
        ),
    ]
