# Generated by Django 5.1 on 2024-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile_picture.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
