# Generated by Django 5.1 on 2024-11-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_waapiinstance'),
        ('users', '0007_userprofile_personal_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waapi_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engage.waapiinstance'),
        ),
    ]
