# Generated by Django 5.1 on 2024-11-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_mobile_phone_userprofile_waapi_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='waapi_instance',
        ),
    ]
