# Generated by Django 5.1 on 2024-11-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignmessage',
            old_name='body',
            new_name='template',
        ),
    ]
