# Generated by Django 5.1 on 2024-11-14 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_waapiinstance'),
        ('users', '0009_remove_userprofile_waapi_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waapiinstance',
            name='user',
        ),
        migrations.AddField(
            model_name='waapiinstance',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waapi_instance', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
