# Generated by Django 5.1 on 2025-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0004_remove_waapiinstance_user_waapiinstance_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesiaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthesia_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('aspect_ratio', models.CharField(default='16:9', max_length=10)),
                ('test', models.BooleanField(default=False)),
                ('script_text', models.TextField()),
                ('avatar', models.CharField(max_length=255)),
                ('avatar_settings', models.JSONField(default=dict)),
                ('background', models.CharField(default='white_studio', max_length=255)),
                ('background_settings', models.JSONField(default=dict)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synthesia_created_at', models.BigIntegerField(blank=True, null=True)),
                ('synthesia_last_updated_at', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail_image', models.URLField(blank=True, null=True)),
                ('thumbnail_gif', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='URL to notify when video is ready', null=True)),
                ('is_ready_for_whatsapp', models.BooleanField(default=False, help_text='Flag indicating video is ready to send via WhatsApp')),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]

