# Generated by Django 5.1 on 2025-03-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0005_synthesiavideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synthesiavideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('sent', 'Sent'), ('scheduled', 'scheduled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
