# Generated by Django 5.1 on 2025-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0006_alter_synthesiavideo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synthesiavideo',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='synthesiavideo',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
