# Generated by Django 5.1 on 2025-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0007_remove_synthesiavideo_webhook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesiavideo',
            name='encrypted_download_url',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiavideo',
            name='encrypted_thumbnail_gif',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synthesiavideo',
            name='encrypted_thumbnail_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
